[build] remove global `set -e`; conflicts with "force" option
in the build subcommands we are already checking the processes' exit
code, and ignore non-zero (failures) when "force" argument is passed.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -16,10 +16,10 @@
 
 source util.sh
 
-# exit early if any sub-commands fails
-set -e
 
 function setup() {
+    # exit early if any sub-commands fails
+    set -e
     if [[ ! $(python -m pip --version 2>/dev/null) ]]; then
         echo >&2 "error: pip is not installed."
         echo >&2 "Try running 'python -m ensurepip' or check installation instructions:"
